# Librerias

In [80]:
# Tratado de datos

import pandas as pd
import numpy as np 

# construccion de datos

import random
from datetime import datetime
from faker import Faker

# Exportacion

from sqlalchemy import create_engine,inspect

# Utiles

In [62]:
# Generamos los datos ficticios en espanhol

fake = Faker('es_ES')

#  Dataset de eventos

In [63]:
# Creamos nuestros datos a utilizar en variables para el dataset de eventos 

id_evento = range(1,501,1)

nombre_evento = ['Pintura divertida','Juegos al sol',
                 'Exploradores','Fiesta de burbujas',
                 'Saltos y risas']

ubicacion =  fake.city()

fecheas = fake.date_between(start_date=datetime(2025, 1, 1), end_date=datetime(2025, 12, 31))

categoria = ['Talleres', 'Salud', 
             'Deportes', 'Cultura',
             'Cine','Viajes']

discapacidad = ['auditiva','física',
                'motora','intelectual',
                'ninguna']

integrantes = random.randint(3, 20)

edades_dirigido = ['0-4','5-8', '9-12', '13-16', '17-20', '21+']

modalidades = ['Interior', 'Aire libre']

precio = round(random.uniform(0, 100)),

In [64]:
# creamos nuestro dataset con un bucle

eventos = []

for i in id_evento:

    nombre = random.choice(nombre_evento)

    if nombre == 'Pintura divertida':
        modalidad = 'Interior'
    elif nombre == 'Fiesta de burbujas':
        modalidad = 'Interior'
    else:
        modalidad = 'Aire libre'


    dicc = {'id_evento' : i,
            'nombre_evento':nombre,
            'ubicacion':fake.city(),
            'fechea':fake.date_between(start_date=datetime(2025, 1, 1), end_date=datetime(2025, 12, 31)),
            'categoria':random.choice(categoria),
            'discapacidad':random.choice(discapacidad),
            'integrantes':random.randint(3, 20),
            'edades':random.choice(edades_dirigido),
            'modalidades':modalidad,
            'precio':round(random.uniform(0, 100)),}
    
    eventos.append(dicc)

df_eventos = pd.DataFrame(eventos)

In [65]:
# Mostramos rl data set

df_eventos

,id_evento,nombre_evento,ubicacion,fechea,categoria,discapacidad,integrantes,edades,modalidades,precio
0,1,Pintura divertida,Teruel,2025-07-20,Cine,física,4,21+,Interior,77
1,2,Saltos y risas,Lleida,2025-02-22,Cultura,intelectual,19,17-20,Aire libre,68
2,3,Fiesta de burbujas,Ciudad,2025-07-22,Salud,intelectual,12,5-8,Interior,82
3,4,Pintura divertida,Santa Cruz de Tenerife,2025-06-01,Cine,auditiva,3,9-12,Interior,98
4,5,Saltos y risas,Sevilla,2025-01-03,Cine,física,3,5-8,Aire libre,83
...,...,...,...,...,...,...,...,...,...,...
495,496,Fiesta de burbujas,Ávila,2025-01-29,Salud,intelectual,9,21+,Interior,34
496,497,Pintura divertida,Navarra,2025-04-29,Cine,motora,11,9-12,Interior,58
497,498,Saltos y risas,Burgos,2025-03-29,Talleres,ninguna,6,13-16,Aire libre,31
498,499,Fiesta de burbujas,Albacete,2025-10-18,Cultura,ninguna,13,5-8,Interior,36
499,500,Saltos y risas,Guadalajara,2025-09-28,Salud,motora,11,13-16,Aire libre,91

# Dataset de usuarios

In [72]:
# Creamos nuestros datos a utilizar en variables para el dataset de usuarios

id_usuario = range(1,201,1)

discapacidad = ['auditiva','física',
                'motora','intelectual',
                'ninguna']

interes = ['Talleres', 'Salud', 
             'Deportes', 'Cultura',
             'Cine','Viajes']

edad_familiares = ['0-4','5-8',
                   '9-12','13-16',
                   '17-20', '21+']

In [70]:
usuarios = []

for i in id_usuario:

    dicc = {'id_usuario': i,
            'nombre_usuario': fake.name(),
            'edad_usuario': random.choice(range(15,40)),
            'edad_familiares': random.choice(edad_familiares),
            'integrantes': random.choice(range(2,5)),
            'discapacidad':random.choice(discapacidad),
            'interes': random.choice(interes),
            'ubicacion':fake.city(),}
    usuarios.append(dicc)

df_usuarios = pd.DataFrame(usuarios)

In [71]:
df_usuarios

,id_usuario,nombre_usuario,edad_usuario,edad_familiares,integrantes,discapacidad,interes,ubicacion
0,1,Armida Amo-Juárez,23,9-12,3,motora,Cultura,Tarragona
1,2,Isaura Pi-Ávila,18,9-12,2,motora,Viajes,Murcia
2,3,Arsenio Adán Cabanillas,36,17-20,3,motora,Deportes,Málaga
3,4,Crescencia Vidal-Merino,19,21+,3,auditiva,Cultura,Salamanca
4,5,Pía Machado Menendez,28,13-16,4,motora,Salud,Madrid
...,...,...,...,...,...,...,...,...
194,195,Hilda Águila-Romeu,26,21+,2,física,Talleres,Toledo
195,196,Agapito de Perelló,30,17-20,3,ninguna,Viajes,Lleida
196,197,Casandra Baró Álamo,29,17-20,3,ninguna,Talleres,Jaén
197,198,Cleto Quintero Moya,34,17-20,3,intelectual,Talleres,Álava
198,199,Dulce Delgado Haro,22,17-20,4,auditiva,Salud,Vizcaya

# Dataset de registros

In [ ]:
id_historial_usuario = range(1,101,1)

In [74]:
historial_usuario = []

for i in id_historial_usuario:
    dicc = {'id_historial_usuario': i,
            'id_usuario': random.choice(df_usuarios['id_usuario']),
            'id_evento': random.choice(df_eventos['id_evento']),
            'interaccion': random.choice([True, False])}
    
    historial_usuario.append(dicc)

df_historial_usuario = pd.DataFrame(historial_usuario)

In [75]:
df_historial_usuario

     id_historial_usuario  id_usuario  id_evento  interaccion
0                       1         104        348         True
1                       2         108        436         True
2                       3         164        357        False
3                       4         142        143         True
4                       5         134        130         True
..                    ...         ...        ...          ...
195                   196          60        253         True
196                   197          73        484        False
197                   198         166        342         True
198                   199         178        480         True
199                   200          77        399        False

[200 rows x 4 columns]

# Exportacion de datos

In [77]:
engine = create_engine('postgresql+psycopg2://postgres:Gabriel@localhost:5432/Dataset_Sinteticos')

In [78]:
df_eventos.to_sql('eventos',engine,if_exists='fail',index=False)
df_usuarios.to_sql('usuarios',engine,if_exists='fail',index=False)
df_historial_usuario.to_sql('registros',engine,if_exists='fail',index=False)

200

In [84]:

inspect(engine).get_table_names()

['eventos', 'usuarios', 'registros']

# Base de datos